# Build stage
FROM golang:1.25-alpine AS builder

ARG VERSION=dev

WORKDIR /app

# Enable greenteagc env
ENV GOENV=greenteagc

# Copy source code and vendor directory
COPY . .

RUN apk --no-cache add ca-certificates tzdata

RUN go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@v1.9.0

RUN /go/bin/cyclonedx-gomod mod -output /app/sbom.cdx.json -json

# Build the binary using vendor directory
RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -ldflags "-X main.version=${VERSION}" -o fakeserver cmd/fakeserver/main.go

# Final stage
FROM scratch

ENV TZ=UTC

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/fakeserver .
COPY --from=builder /app/sbom.cdx.json .
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/share/zoneinfo/UTC /usr/share/zoneinfo/UTC

# Expose the default port
EXPOSE 9001

# Run the binary
ENTRYPOINT ["./fakeserver"]